# Generated by Django 5.2.6 on 2025-12-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_investmentcategory_investment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
