# Generated by Django 5.2.6 on 2025-12-13 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_investmentbenefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentbenefits',
            name='investment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='accounts.investment'),
        ),
    ]
