# Generated by Django 5.2.6 on 2025-12-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_investmentbenefits_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
