# Generated by Django 5.2.6 on 2025-12-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_investment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
