# Generated by Django 5.2.6 on 2025-12-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_investment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='roi_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
