# Generated by Django 5.2.6 on 2025-12-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_investment_roi_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='roi_rate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
