# Generated by Django 5.2.6 on 2025-12-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_investment_roi_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referral_Link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
