# Generated by Django 5.2.6 on 2025-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_client_referral_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
