# Generated by Django 5.2.6 on 2025-12-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_investment_is_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_deposit',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
