# Generated by Django 5.2.6 on 2025-12-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_first_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_deposit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
