# Generated by Django 5.2.6 on 2025-09-10 13:11

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_client_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='US', max_length=2, null=True),
        ),
    ]
