# Generated by Django 5.2.6 on 2025-09-10 13:21

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_client_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='main_balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=19),
        ),
    ]
