# Generated by Django 5.2.6 on 2025-09-12 22:05

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='main_balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=19),
        ),
    ]
