# Generated by Django 5.2.6 on 2025-09-12 22:07

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_main_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bonus',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=19),
        ),
        migrations.AlterField(
            model_name='account',
            name='book_balance',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=19),
        ),
        migrations.AlterField(
            model_name='account',
            name='main_balance',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=19),
        ),
        migrations.AlterField(
            model_name='account',
            name='roi_balance',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=19),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_amount_deposited',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=19),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_amount_investment',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=19),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_amount_withdrawn',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=19),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_expected_roi',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=19),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_roi_received',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=19),
        ),
    ]
