# Generated by Django 5.2.6 on 2025-09-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_investment_paymentmethods_investment_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
