# Generated by Django 5.2.6 on 2025-09-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_verificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123, null=True)),
                ('wallet_address', models.CharField(max_length=200, null=True)),
                ('wallet_qr_code', models.ImageField(blank=True, null=True, upload_to='admin_wallet/')),
            ],
        ),
    ]
