# Generated by Django 5.2.6 on 2025-09-18 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_adminwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=100, null=True)),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode/Zipcode')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('state', models.CharField(max_length=150, verbose_name='State')),
                ('document_type', models.CharField(choices=[('Driver License', 'Driver License'), ('National ID', 'National ID'), ('Passport', 'Passport')], max_length=50, null=True)),
                ('id_front_view', models.FileField(null=True, upload_to='kyc/%Y-%m-%d/')),
                ('id_back_view', models.FileField(blank=True, null=True, upload_to='kyc/%Y-%m-%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='accounts.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYCs',
            },
        ),
    ]
