# Generated by Django 5.2.6 on 2025-09-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('forwarding_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
