# Generated by Django 5.2.6 on 2025-09-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_companyprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='domain',
            field=models.URLField(blank=True, max_length=20, null=True),
        ),
    ]
