# Generated by Django 5.2.6 on 2025-09-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_companyprofile_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
    ]
