# Generated by Django 5.2.6 on 2025-09-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_companyprofile_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
