# Generated by Django 5.2.6 on 2025-09-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_kyc_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/avatar.png', null=True, upload_to='client/profile_pic'),
        ),
    ]
