# Generated by Django 5.2.6 on 2025-09-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_client_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/avartar.png', null=True, upload_to='client/profile_pic'),
        ),
    ]
