# Generated by Django 5.2.6 on 2025-09-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_client_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
