# Generated by Django 5.2.6 on 2025-09-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_client_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
